import { OrderAgent } from '../agents/orderAgent.js'
import { BillingAgent } from '../agents/billingAgent.js'
import { SupportAgent } from '../agents/supportAgent.js'
import { routerService } from './routerService.js'
import type { RoutingResult } from '../types/agents.js'

const orderAgent = new OrderAgent()
const billingAgent = new BillingAgent()
const supportAgent = new SupportAgent()

export class AgentService {
    async processMessage(
        userMessage: string,
        conversationContext?: string
    ): Promise<{ response: string; routing: RoutingResult }> {
        // console.log('='.repeat(80))
        // console.log('ROUTING REQUEST')
        // console.log('Message:', userMessage)
        // console.log('Has Context:', !!conversationContext)
        // console.log('='.repeat(80))

        const routing = await routerService.routeMessage(userMessage)

        // console.log(`Delegating to ${routing.agent.toUpperCase()} agent...`)

        let response: string

        switch (routing.agent) {
            case 'order':
                response = await orderAgent.handle(userMessage, conversationContext)
                break
            case 'billing':
                response = await billingAgent.handle(userMessage, conversationContext)
                break
            case 'support':
            default:
                response = await supportAgent.handle(userMessage, conversationContext)
                break
        }

        // console.log(`Response generated by ${routing.agent} agent`)
        // console.log('='.repeat(80))

        return { response, routing }
    }

    async processMessageStream(
        userMessage: string,
        conversationContext?: string
    ) {
        // console.log('='.repeat(80))
        // console.log('STREAMING ROUTING REQUEST')
        // console.log('Message:', userMessage)
        // console.log('Has Context:', !!conversationContext)
        // console.log('='.repeat(80))

        const routing = await routerService.routeMessage(userMessage)

        // console.log(`Delegating to ${routing.agent.toUpperCase()} agent for streaming...`)

        let stream

        switch (routing.agent) {
            case 'order':
                stream = await orderAgent.handleStream(userMessage, conversationContext)
                break
            case 'billing':
                stream = await billingAgent.handleStream(userMessage, conversationContext)
                break
            case 'support':
            default:
                stream = await supportAgent.handleStream(userMessage, conversationContext)
                break
        }

        return { stream, routing }
    }
}

export const agentService = new AgentService()
